repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--extend-select=I, --fix, ./bot-service]
      # Run the formatter.
      - id: ruff-format
        args: [./bot-service]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Check for the latest version
    hooks:
      - id: prettier
        args: ["--write", "./connector-service"]

  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint
        language: system
        entry: bash
        args: ["-c", "cd ./connector-service && npx eslint --fix"]
        pass_filenames: false
