services:
  bot-service:
    container_name: bot-service
    build:
      context: bot-service
      dockerfile: Dockerfile
    networks:
      - bot_network
    depends_on:
      - db
  connector-service:
    container_name: connector-service
    build:
      context: connector-service
      dockerfile: Dockerfile
    networks:
      - bot_network
    depends_on:
      - bot-service
  db:
    container_name: db
    image: postgres:13
    env_file:
      - ./bot-service/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network
volumes:
  db_data:
networks:
  bot_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
