services:
  bot-service:
    container_name: bot-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bot_network
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network
volumes:
  db_data:
networks:
  bot_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24